/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ventana2.java
 *
 * Created on 07/04/2011, 15:00:38
 */

package irobot;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;

import javax.swing.JOptionPane;

import lejos.nxt.*;
import lejos.nxt.remote.NXTCommand;
import lejos.pc.comm.*;

/**
 *
 * @author Victor
 */
public class Ventana2 extends javax.swing.JFrame implements ActionListener {

	private boolean conectado = false;
    /**
	 * 
	 */
	private static final long serialVersionUID = 201104071521L;
	/** Creates new form Ventana2 */
    public Ventana2() {
        initComponents();
        
        WindowAdapter oyenteCierraVentana = new java.awt.event.WindowAdapter() {
			public void windowClosing (WindowEvent e) {
				this_windowClosing(e);
			}
		};
		this.addWindowListener(oyenteCierraVentana);
		
    }
    
	

	public void actionPerformed(ActionEvent arg0) {
	}
	
	public void botonConectar_actionPerformed(ActionEvent e) {
		conectado = true;
		jB_Conectar.setEnabled(!conectado);
		jB_Desconectar.setEnabled(conectado);
		jTF_NombreNXT.setEnabled(!conectado);
		
		conn = new NXTConnector();

	    if (!conn.connectTo("NXT", NXTComm.LCP)) {
	      System.err.println("Conexión Fallida");
	      //System.exit(1);
	      conectado = false;
	      jB_Desconectar.setEnabled(conectado);
			jB_Conectar.setEnabled(!conectado);
			jTF_NombreNXT.setEnabled(!conectado);
	    }
	    NXTCommand.getSingleton().setNXTComm(conn.getNXTComm());
		
	}
	
	public void botonDesconectar_actionPerformed(ActionEvent e) {	
		conectado = false;
		jB_Desconectar.setEnabled(conectado);
		jB_Conectar.setEnabled(!conectado);
		jTF_NombreNXT.setEnabled(!conectado);
		try {
			conn.close();
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
			conectado = true;
			jB_Conectar.setEnabled(!conectado);
			jB_Desconectar.setEnabled(conectado);
			jTF_NombreNXT.setEnabled(!conectado);
		}
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_Log = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jP_Joystick = new javax.swing.JPanel();
        jL_MotorA = new javax.swing.JLabel();
        jL_MotorB = new javax.swing.JLabel();
        jL_MotorC = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jB_Salir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jB_Conectar = new javax.swing.JButton();
        jB_Desconectar = new javax.swing.JButton();
        jTF_NombreNXT = new javax.swing.JTextField();
        jL_NombreNXT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:: iRobot ::. - v");
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(200, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 400));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(180, 32767));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(180, 23));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(180, 96));

        jTA_Log.setColumns(20);
        jTA_Log.setEditable(false);
        jTA_Log.setRows(5);
        jTA_Log.setPreferredSize(new java.awt.Dimension(170, 94));
        jScrollPane1.setViewportView(jTA_Log);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setMaximumSize(new java.awt.Dimension(220, 400));
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(220, 400));

        jP_Joystick.setBackground(new java.awt.Color(153, 153, 153));
        jP_Joystick.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jP_Joystick.setMaximumSize(new java.awt.Dimension(200, 200));
        jP_Joystick.setMinimumSize(new java.awt.Dimension(200, 200));
        jP_Joystick.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jP_JoystickLayout = new javax.swing.GroupLayout(jP_Joystick);
        jP_Joystick.setLayout(jP_JoystickLayout);
        jP_JoystickLayout.setHorizontalGroup(
            jP_JoystickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jP_JoystickLayout.setVerticalGroup(
            jP_JoystickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        jL_MotorA.setText("Motor A:");

        jL_MotorB.setText("Motor B:");

        jL_MotorC.setText("Motor C:");

        jTextField1.setEditable(false);

        jTextField2.setEditable(false);

        jTextField3.setEditable(false);

        jB_Salir.setText("Salir");
        jB_Salir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(ActionEvent e) {
				System.exit(0);
			}
		});
        
        jB_Conectar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(ActionEvent e) {
				botonConectar_actionPerformed(e);
			}
		});
        
        jB_Desconectar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(ActionEvent e) {
				botonDesconectar_actionPerformed(e);
			}
		});
        

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Salir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jL_MotorC, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jL_MotorB, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jL_MotorA, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jP_Joystick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jP_Joystick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_MotorA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_MotorB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_MotorC))
                .addGap(18, 18, 18)
                .addComponent(jB_Salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(426, 41));

        jB_Conectar.setText("Conectar");
        jB_Conectar.setMaximumSize(new java.awt.Dimension(93, 23));
        jB_Conectar.setMinimumSize(new java.awt.Dimension(93, 23));
        jB_Conectar.setPreferredSize(new java.awt.Dimension(93, 23));

        jB_Desconectar.setText("Desconectar");
        jB_Desconectar.setEnabled(false);

        jL_NombreNXT.setText("Nombre NXT:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_Conectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Desconectar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jL_NombreNXT)
                .addGap(18, 18, 18)
                .addComponent(jTF_NombreNXT, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Conectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Desconectar)
                    .addComponent(jTF_NombreNXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_NombreNXT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, 0, 352, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	public void this_windowClosing(WindowEvent e) {
		System.exit(0);
	}
	
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Ventana2().setVisible(true);
                Ventana2 ventana = new Ventana2();
        		ventana.pack();
        		//ventana.setResizable(false);
        		ventana.setVisible(true);
        		ventana.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Conectar;
    private javax.swing.JButton jB_Desconectar;
    private javax.swing.JButton jB_Salir;
    private javax.swing.JLabel jL_MotorA;
    private javax.swing.JLabel jL_MotorB;
    private javax.swing.JLabel jL_MotorC;
    private javax.swing.JLabel jL_NombreNXT;
    private javax.swing.JPanel jP_Joystick;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA_Log;
    private javax.swing.JTextField jTF_NombreNXT;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private NXTConnector conn;
}
